name: Trigger Deployment

on:
  push:
    branches:
      - latest
      - smartgit/*

permissions:
  contents: write
  actions: write

jobs:
  dispatch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches \
            -d '{"ref": "main"}'
